export default {
  LIST: "LIST",
  CARD: "CARD",
  FETCH_LISTS: "FETCH_LISTS",
  ADD_COLUMN: "ADD_COLUMN",
  ADD_CARD: "ADD_CARD",
  SHIFT_CARD: "SHIFT_CARD",
  REMOVE_CARD: "REMOVE_CARD",
  REMOVE_COLUMN: "REMOVE_COLUMN",
  SWAP_CARD: "SWAP_CARD",
  SWAP_LIST: "SWAP_LIST"
};
